smart/config/routes.rb
Rails.application.routes.draw do

  resources :attends do
    collection do
      get :start
    end
    member do
      get :finish
      get :rest_time_start
      get :rest_time_end
    end
  end

  devise_for :staffs
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  
  root to: "home#index"
  resources :home
  # root 'home#index'

    #就業規則情報
  resources :rules
  # root 'rules#index'
  
    #会社基本情報・助成金作成情報
  resources :managements
  # root 'managements#index'

    #各従業員情報・雇用契約書情報
  resources :workers do
    member do
      get :print
    end
  end
  # root 'workers#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

smart/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	 @current = Time.now 
     @current_attend = current_user.attends.started.last if current_user.present?
  end

  def show
  end
end

smart/app/helpers/home_helper.rb
module HomeHelper
end

smart/app/views/home/index.html.erb
<div id = "time_now">
<%= @current.strftime('%Y年%m月%d日 %X %a') %>
</div>
<div class="stumps">
	<!-- <div class="square_btn stump">出勤</div> -->
  <%- if @current_attend.present? -%>
    <div class="square_btn stump">出勤</div>
  <%- else -%>
    <%= link_to("出勤", start_attends_path, class: "square_btn stump") %>
  <%- end -%>
	<!-- <div class="square_btn stump">休憩開始</div> -->
	<!-- <div class="square_btn stump">休憩終了</div> -->
	<!-- <div class="square_btn stump">退勤</div> -->
  <%- if @current_attend.present? -%>
    <%- if @current_attend.rest_start_at.blank? -%>
      <%= link_to("休憩開始", rest_time_start_attend_path(@current_attend), class: "square_btn stump") %>
      <div class="square_btn stump">休憩終了</div>
    <%- else -%>
      <div class="square_btn stump">休憩開始</div>
      <%- if @current_attend.rest_end_at.blank? -%>
        <%= link_to("休憩終了", rest_time_end_attend_path(@current_attend), class: "square_btn stump") %>
      <%- else -%>
        <div class="square_btn stump">休憩終了</div>
      <%- end -%>
    <%- end -%>
    <%= link_to("退勤", finish_attend_path(current_user.attends.started.last), class: "square_btn stump") %>
  <%- else -%>
    <div class="square_btn stump">休憩開始</div>
    <div class="square_btn stump">休憩終了</div>
    <div class="square_btn stump" disabled>退勤</div>
  <%- end -%>
  <br/>
  <%# print_worker_path(1) の1は暫定的に設定。実際はworkerの当該IDをセットすること %>
  <%- if current_user.present? && current_user.attends.exists? -%>
    <%= link_to("テストプリント", print_worker_path(1), class: "square_btn stump", target: "_blank") %>
  <%- end -%>
</div>

smart/app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>