smart/config/routes.rb
Rails.application.routes.draw do

  resources :attends do
    collection do
      get :start
    end
    member do
      get :finish
      get :rest_time_start
      get :rest_time_end
    end
  end

  devise_for :staffs
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  
  root to: "home#index"
  resources :home
  # root 'home#index'

    #就業規則情報
  resources :rules
  # root 'rules#index'
  
    #会社基本情報・助成金作成情報
  resources :managements
  # root 'managements#index'

    #各従業員情報・雇用契約書情報
  resources :workers do
    member do
      get :print
    end
  end
  # root 'workers#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

smart/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang = "ja">
 <head>
       <title>勤怠管理システム『SMART』労働基準法を遵守した唯一の勤怠管理システム</title>
              <meta charset="utf-8">
              <!--　レスポンシブの定義　-->
               <meta name="viewport" content="width=device-width, initial-scale=1,0">
    
               <%= csrf_meta_tags %>

               <link rel="stylesheet" href="application.scss">
               <link rel="stylesheet" href="workers.scss">
                <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
                 <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<header>
    <div class="container">
      <div class="header-left">
        <%= image_tag("rogo.jpg", :class => "menu_icon") %>
      </div>
      <div class="header-right">
        <!-- user/signed_in? はユーザーがログインしているか調べるdeviseのHelperメソッド -->
            
           <%= link_to  'ホーム', '/home' %>
           <%= link_to  '出勤簿', '/shift' %>
                    <!-- シフト表・出勤簿・シフト作成-->
            <%= link_to  '賃金台帳', '/salary' %>
                    <!-- 給与明細・給与編集・賃金台帳・賞与台帳-->
            <%= link_to  '有給', '/vacance' %>
                    <!-- 有給情報・有給許可申請・有給台帳-->
            <%= link_to  '日報', '/report' %>
           <%= link_to  '情報登録', 'information'  %>
                    <!-- 従業員情報登録・従業員情報編集・事業所情報編集・就業情報編集-->
           <%= link_to  '事業所登録' ,'/managements'%>
           <%= link_to  '就業規則作成' ,'/rules'%>
           <%= link_to  '従業員登録' ,'/workers'%>
           
            <% if user_signed_in? %>
            <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
            <!-- *_path はUserモデルを作成したときに、deviseにより自動で作成されてますので、rake routesで確認できます -->
                    <strong><% current_user.email  %></strong>
                        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            <% else %>
                        <%= link_to "ログイン", new_user_session_path%>
             <% end %>
      </div>
    </div>

</header>

<body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
</body>
</html>

smart/app/views/layouts/staffs.html.erb
<!DOCTYPE html>
<html lang = "ja">
 <head>
       <title>勤怠管理システム『SMART』労働基準法を遵守した唯一の勤怠管理システム</title>
              <meta charset="utf-8">
              <!--　レスポンシブの定義　-->
               <meta name="viewport" content="width=device-width, initial-scale=1,0">
    
               <%= csrf_meta_tags %>

               <link rel="stylesheet" href="application.scss">
               <link rel="stylesheet" href="workers.scss">
                <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
                 <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<header>
    <div class="container">
      <div class="header-left">
        <%= image_tag("rogo.jpg", :class => "menu_icon") %>
      </div>
      <div class="header-right">
        <!-- user/signed_in? はユーザーがログインしているか調べるdeviseのHelperメソッド -->
            
           <%= link_to  'ホーム', '/home' %>
           <%= link_to  '出勤簿', '/shift' %>
                    <!-- シフト表・出勤簿・シフト作成-->
            <%= link_to  '賃金台帳', '/salary' %>
                    <!-- 給与明細・給与編集・賃金台帳・賞与台帳-->
            <%= link_to  '有給', '/vacance' %>
                    <!-- 有給情報・有給許可申請・有給台帳-->
            <%= link_to  '日報', '/report' %>
           <%= link_to  '情報登録', 'information'  %>
                    <!-- 従業員情報登録・従業員情報編集・事業所情報編集・就業情報編集-->
           <%= link_to  '事業所登録' ,'/managements'%>
           <%= link_to  '就業規則作成' ,'/rules'%>
           <%= link_to  '従業員登録' ,'/workers'%>
           
            <% if staff_signed_in? %>
            <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
            <!-- *_path はUserモデルを作成したときに、deviseにより自動で作成されてますので、rake routesで確認できます -->
                    <strong><% current_user.email  %></strong>
                        <%= link_to "ログアウト", destroy_staff_session_path, method: :delete %>
            <% else %>
                        <%= link_to "ログイン(staff)", new_staff_session_path%>
             <% end %>
      </div>
    </div>

</header>

<body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
</body>
</html>