smart/config/routes.rb
Rails.application.routes.draw do

  resources :attends do
    collection do
      get :start
    end
    member do
      get :finish
      get :rest_time_start
      get :rest_time_end
    end
  end

  devise_for :staffs
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  
  root to: "home#index"
  resources :home
  # root 'home#index'

    #就業規則情報
  resources :rules
  # root 'rules#index'
  
    #会社基本情報・助成金作成情報
  resources :managements
  # root 'managements#index'

    #各従業員情報・雇用契約書情報
  resources :workers do
    member do
      get :print
    end
  end
  # root 'workers#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

smart/app/models/attend.rb
class Attend < ApplicationRecord
  belongs_to :user

  scope :started, -> { where(end_at: nil).order(:start_at) }
end

smart/app/controllers/attends_controller.rb
class AttendsController < MainController
  before_action :set_attend, only: [:show, :edit, :update, :destroy, :rest_time_start, :rest_time_end]

  # GET /attends
  # GET /attends.json
  def index
    @attends = Attend.all
  end

  # GET /attends/1
  # GET /attends/1.json
  def show
  end

  # GET /attends/new
  def new
    @attend = Attend.new
  end

  # GET /attends/1/edit
  def edit
  end

  # POST /attends
  # POST /attends.json
  def create
    @attend = Attend.new(attend_params)
    # @attend = Attend.new(user: current_user, start_at: Time.current)

    respond_to do |format|
      if @attend.save
        format.html { redirect_to @attend, notice: 'Attend was successfully created.' }
        # format.html { redirect_to root_path, notice: 'Attend was successfully created.' }
        format.json { render :show, status: :created, location: @attend }
      else
        format.html { render :new }
        # format.html { redirect_to root_path, notice: 'Attend was successfully created.' }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attends/1
  # PATCH/PUT /attends/1.json
  def update
    respond_to do |format|
      if @attend.update(attend_params)
        format.html { redirect_to @attend, notice: 'Attend was successfully updated.' }
        format.json { render :show, status: :ok, location: @attend }
      else
        format.html { render :edit }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attends/1
  # DELETE /attends/1.json
  def destroy
    @attend.destroy
    respond_to do |format|
      format.html { redirect_to attends_url, notice: 'Attend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def start
    @attend = Attend.new(user: current_user, start_at: Time.current)

    respond_to do |format|
      if @attend.save
        format.html { redirect_to root_path, notice: 'Attend was successfully created.' }
      else
        format.html { redirect_to root_path, errors: @attend.errors }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
      end
    end
  end

  def finish
    # @attend = current_user.attends.find_by("attends.start_at >= ? and attends.end_at = ?", Time.current.at_beginning_of_day, nil)
    @attend = current_user.attends.started.last
    @attend.end_at = Time.current

    respond_to do |format|
      if @attend.save
        format.html { redirect_to root_path, notice: 'Attend was successfully updated.' }
      else
        format.html { redirect_to root_path, errors: @attend.errors }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
      end
    end
  end

  def rest_time_start
    @attend.rest_start_at = Time.current

    respond_to do |format|
      if @attend.save
        format.html { redirect_to root_path, notice: 'Attend.rest_start_at was successfully updated.' }
      else
        format.html { redirect_to root_path, errors: @attend.errors }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
      end
    end
  end
  def rest_time_end
    @attend.rest_end_at = Time.current

    respond_to do |format|
      if @attend.save
        format.html { redirect_to root_path, notice: 'Attend.rest_end_at was successfully updated.' }
      else
        format.html { redirect_to root_path, errors: @attend.errors }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attend
      @attend = Attend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attend_params
      params.require(:attend).permit(:user_id, :start_at, :end_at)
    end
end

smart/app/helpers/attends_helper.rb
module AttendsHelper
end

smart/app/views/attends/_form.html.erb
<%= form_with(model: attend, local: true) do |form| %>
  <% if attend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attend.errors.count, "error") %> prohibited this attend from being saved:</h2>

      <ul>
      <% attend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :attend_user_id %>
  </div>

  <div class="field">
    <%= form.label :start_at %>
    <%= form.datetime_select :start_at, id: :attend_start_at %>
  </div>

  <div class="field">
    <%= form.label :end_at %>
    <%= form.datetime_select :end_at, id: :attend_end_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

smart/app/views/attends/edit.html.erb
<h1>Editing Attend</h1>

<%= render 'form', attend: @attend %>

<%= link_to 'Show', @attend %> |
<%= link_to 'Back', attends_path %>

smart/app/views/attends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attends</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Start at</th>
      <th>End at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attends.each do |attend| %>
      <tr>
        <td><%= attend.user %></td>
        <td><%= attend.start_at %></td>
        <td><%= attend.end_at %></td>
        <td><%= link_to 'Show', attend %></td>
        <td><%= link_to 'Edit', edit_attend_path(attend) %></td>
        <td><%= link_to 'Destroy', attend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attend', new_attend_path %>

smart/app/views/attends/new.html.erb
<h1>New Attend</h1>

<%= render 'form', attend: @attend %>

<%= link_to 'Back', attends_path %>

smart/app/views/attends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @attend.user %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @attend.start_at %>
</p>

<p>
  <strong>End at:</strong>
  <%= @attend.end_at %>
</p>

<%= link_to 'Edit', edit_attend_path(@attend) %> |
<%= link_to 'Back', attends_path %>